# Generated by Django 4.1.4 on 2023-10-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=60)),
                ('prix', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
