# Generated by Django 4.1.4 on 2023-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.FileField(upload_to='livre'),
        ),
    ]
